# Pandas_Starter

## 1. Object Creation : Series

In [1]:
import numpy as np
import pandas as pd

data1 = pd.Series([2, 4, 6, 7, 8, np.nan])

print(data1)

0    2.0
1    4.0
2    6.0
3    7.0
4    8.0
5    NaN
dtype: float64


In [8]:
np.array([2,4, 6, 7, 8, np.nan])

array([ 2.,  4.,  6.,  7.,  8., nan])

In [7]:
data1.values                     # print series values           

array([ 2.,  4.,  6.,  7.,  8., nan])

In [9]:
data1.index                      # print series index                               

RangeIndex(start=0, stop=6, step=1)

In [10]:
data1[3]                         # indexing

7.0

In [11]:
data1[1:4]                       # slicing

1    4.0
2    6.0
3    7.0
dtype: float64

### B. Custom Indexing

In [ ]:

data2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'z', 'g'])

print(data2)

### C. Data can be scalar

In [ ]:

data3 = pd.Series(5, index=[100, 200, 300])

print(data3)

### D. Converting Dictionary to Series

In [ ]:
population_dict = {'Bangalore': 38332521,
                   'Delhi': 26448193,
                   'Kolkota': 19651127,
                   'Chennai' : 19552839,
                   'Hyderabad' : 12882135}

population = pd.Series(population_dict)

population

p

In [ ]:
population['Delhi']

In [ ]:
population['Bangalore':'Chennai']

## 2. Object Creation : Dataframe

### A. From dictionary of Series objects

In [12]:
area_dict = {'Bangalore': 743033,
             'Delhi': 849393,
             'Kolkota': 984833,
             'Chennai' : 932849,
             'Hyderabad' : 839390}

population_dict = {'Bangalore': 38332521,
                   'Delhi': 26448193,
                   'Kolkota': 19651127,
                   'Chennai' : 19552839,
                   'Hyderabad' : 12882135}

area = pd.Series(area_dict)
population = pd.Series(population_dict)

city = pd.DataFrame({'Population': population, 'Area': area})
print("\n population :  \n" , population)
print("\n area : \n",area)
print("\n city \n" ,city)


 population :  
 Bangalore    38332521
Delhi        26448193
Kolkota      19651127
Chennai      19552839
Hyderabad    12882135
dtype: int64

 area : 
 Bangalore    743033
Delhi        849393
Kolkota      984833
Chennai      932849
Hyderabad    839390
dtype: int64

 city 
            Population    Area
Bangalore    38332521  743033
Delhi        26448193  849393
Kolkota      19651127  984833
Chennai      19552839  932849
Hyderabad    12882135  839390


In [13]:
city

Population    Area
Bangalore    38332521  743033
Delhi        26448193  849393
Kolkota      19651127  984833
Chennai      19552839  932849
Hyderabad    12882135  839390

In [14]:
city.index                        # print Index

Index(['Bangalore', 'Delhi', 'Kolkota', 'Chennai', 'Hyderabad'], dtype='object')

In [15]:
city.columns                      # Print Colums

Index(['Population', 'Area'], dtype='object')

In [16]:
city.values

array([[38332521,   743033],
       [26448193,   849393],
       [19651127,   984833],
       [19552839,   932849],
       [12882135,   839390]], dtype=int64)

In [17]:
city.keys()

Index(['Population', 'Area'], dtype='object')

- keys
- values
- features
- labels 

In [18]:
# DataFrame as Specialized Dicitonary 

print(city['Area'])                     # indexing

Bangalore    743033
Delhi        849393
Kolkota      984833
Chennai      932849
Hyderabad    839390
Name: Area, dtype: int64


In [19]:
city[['Area']]


Area
Bangalore  743033
Delhi      849393
Kolkota    984833
Chennai    932849
Hyderabad  839390

In [20]:
city.Area

Bangalore    743033
Delhi        849393
Kolkota      984833
Chennai      932849
Hyderabad    839390
Name: Area, dtype: int64

### B. From a two-dimensional NumPy array

In [21]:
df1 = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])

df1

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [23]:
grid = np.random.randint(10,size = (3,2)) 

A = pd.DataFrame(grid,columns=['foo', 'bar'],index=['a', 'b', 'c'])

print(A)

A

   foo  bar
a    4    5
b    2    5
c    7    0


foo  bar
a    4    5
b    2    5
c    7    0

In [28]:
df = pd.DataFrame(np.random.randint(10, size = (4,4)), columns = ['key1','key2','key3','key4'], index = ['a','b','c','d'])
df

key1  key2  key3  key4
a     0     2     9     9
b     0     4     8     9
c     9     7     7     8
d     0     2     6     0

In [30]:
df = pd.DataFrame(np.random.randint(90, size = (5,5)),columns = ['name','city','area','pop','local'], index = ['1','2','3','4','5',])
df

name  city  area  pop  local
1     5    19    48   29     79
2    34    48    53   78     82
3    88    84    88   16      3
4    72    56    61   22      8
5    87    24     5   86     72