# The Basics of Numpy Array
1. Attributes of Arrays
2. Indexing of Arrays
3. Slicing of Arrays
4. Reshapng of Arrays
5. Joining of Arrays 
6. Splitting Arrays

### 1. Attributes of Array 
(Determine Size, Shape, memory consumption, dimention and data types)                        

In [1]:
import numpy as np
np.random.seed(0)

m1 = np.random.randint(10, size=6)                 # one dimensional array
m2 = np.random.randint(10, size=(3, 4))            # two dimensional array
m3 = np.random.randint(10, size =(3, 4, 5))        # three dimensional array

print("m3 dimention:", m3.ndim)    
print("m3 shape:", m3.shape)
print("m3 size:", m3.size)
print("m3 data type:", m3.dtype)
print("Itemsize: ", m3.itemsize, "bytes")          # size of each element in array in bytes
print("Total size of array", m3.nbytes, "bytes")   # Total size of array in bytes


m3 dimention: 3
m3 shape: (3, 4, 5)
m3 size: 60
m3 data type: int32
Itemsize:  4 bytes
Total size of array 240 bytes
(80, 20, 4)


### 2. Indexing of Array

In [5]:
# Accessing particular element of one dimensional array
print(m1)
m1[-2]


[5 0 3 3 7 9]


7

In [4]:
# Accessing particular element of two dimensional array
print(m2)
m2[2,3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


7

In [6]:
# modifying the element of array

m2[2, 3] = 34
print(m2)

[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 34]]


### 3. Slicing of Array

In [8]:
# one dimensional sub arrays
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
x[:6]            # first six elements

array([0, 1, 2, 3, 4, 5])

In [10]:
x[4:]            # elements after index 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
x[3:7]           # middle sub-array

array([3, 4, 5, 6])

In [12]:
x[::3]           # Every other element

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
x[6::2]          # Every other element, Starting at index 6

array([ 6,  8, 10, 12, 14, 16, 18])

In [14]:
x[::-1]          # slicing in reverse order with negative step value

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [19]:
x[5::-2]          # reversing from an index value

array([5, 3, 1])

In [15]:
# Multi-dimensional sub arrays
m2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 34]])

In [23]:
m2[:3,:2]  # slicing 3 rows and 2 columns

array([[3, 5],
       [7, 6],
       [1, 6]])

In [24]:
m2[1:,2:]

array([[ 8,  8],
       [ 7, 34]])

In [18]:
m2[:3, ::2]      # all rows and every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [20]:
m2[:-1, :-2]    # slicing unwanted rows and column

array([[3, 5],
       [7, 6]])

NOTE: Changes in the subarray changes in the main array also in Numpy unlike List in python
      So, a copy of sub array must be made to prevent change in the main array 

In [25]:
m2_copy_array = m2[:2, :2].copy()
m2_copy_array[0,0] = 99
m2_copy_array                            # check by replacing this to m2

array([[99,  5],
       [ 7,  6]])

In [26]:
# Slicing a complete column
m2[:, 2]      

array([2, 8, 7])

In [27]:
# Slicing a complete row
m2[1, :]       

array([7, 6, 8, 8])

### 4. Reshaping of Array

In [32]:
# Reshaping particular array to required order

matrices = np.arange(1,17).reshape((4, 4))
print(matrices)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [29]:
# Reshaping particular array to required order and dimension

print(np.arange(60).reshape(3, 4, 5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [33]:
# Conversion of one dimensional array into two dimensional row or column matrix
x=np.array([2, 4, 6]).reshape((1,3))
x.shape                     # row vector via reshape

(1, 3)

### 5. Joining or Concatenation of  Arrays

In [34]:
# Joining two single dimensial array
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
np.concatenate([a, b])


array([2, 4, 6, 8, 1, 3, 5, 7])

In [35]:
# Concatenating more than two array
c = np.array([23, 23, 23])
np.concatenate([a, b, c])

array([ 2,  4,  6,  8,  1,  3,  5,  7, 23, 23, 23])

In [36]:
# Joining two dimentional array
matrix = np.array([[2, 4, 6],
                  [1, 3, 5]])

np.concatenate([matrix, matrix])     # Concatenation along first axis

array([[2, 4, 6],
       [1, 3, 5],
       [2, 4, 6],
       [1, 3, 5]])

In [37]:
np.concatenate([matrix, matrix], axis = 1)  # Concatenation along second axis

array([[2, 4, 6, 2, 4, 6],
       [1, 3, 5, 1, 3, 5]])

In [39]:
# Joining arrays of mixed dimension
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [7, 8, 9]])

# Vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
y = np.array([[23], 
              [23]])

# Horizontally stack the arrays
print(np.hstack([grid, y]))

[[ 4  5  6 23]
 [ 7  8  9 23]]


### 6. Splitting of  Arrays

In [41]:
# Splitting array to subarrays single dimension
s = np.arange(20)
print(s)

s1, s2, s3, s4, s5 = np.split(s, [2, 5, 8, 15])     # N split points produce N+1 Subarrays
print(s1, s2, s3, s4, s5)                           # Split points represent no of elements

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1] [2 3 4] [5 6 7] [ 8  9 10 11 12 13 14] [15 16 17 18 19]


In [46]:
mat = np.arange(16).reshape((4,4))
print(mat)

# Spliting array in horizontal
top, down = np.vsplit(mat, [3])
print(top)
print(down)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
# Spliting array in vertical
left, right = np.hsplit(mat, [3])
print(left)
print(right)