# Numpy : Array Creation

In [2]:
import numpy as np
M = np.array([[2, 4, 6, 8],
             [1, 2, 3, 4]])
print(M)                         # Array 

# Create Matrix from data
print(np.mat(M))                 # Matrix

[[2 4 6 8]
 [1 2 3 4]]
[[2 4 6 8]
 [1 2 3 4]]


### 1. Random filled data

In [3]:
# random filled data
print(np.empty((3,3)))                  

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.25685847e-321]
 [4.46811701e-091 2.44041271e-154 7.13637444e+159]]


In [4]:
# random with dtype argument
# explicitly coverting to int

print(np.empty((3,3), dtype=int))      

[[  -1268592        354 1659706832]
 [     32761 1659708768      32761]
 [1659812928      32761 1659704480]]


### 2. Zero Matrix

In [7]:
# Create zero matrix of zeros

print(np.zeros((4,3)))                 

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Matrix of Value one

In [8]:
# Create martrix of ones 

print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4. Matrix with ones on the diagonal and zeros elsewhere 

In [9]:
np.eye(4,dtype = int)                     # Try passing argument K

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### 5. Identity matrix

In [10]:
# The square identity matrix of given size

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 6. Diagonal matrix

In [11]:
# kth Diagonal Matrix

d1 = np.array([1,2,3,4])   # 1-D array          
 
d2 = np.array([[1,2,3],    # 2-D array
               [2,2,2]])

print(np.diag(d1, k=1))      # kth diagonal if input is a 1-D array

print(np.diag(d2, k=1))      # kth diagonal if input is a 1-D array

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
[2 2]


### 7. Array of given shape and type, filled with fill_value.

In [12]:
f1 = np.full((2, 2), np.inf)             
print(f1)

f2 = np.full((3, 4), 24)             
print(f2)

f3 = np.full((3, 4), 's')             
print(f3)

[[inf inf]
 [inf inf]]
[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]
[['s' 's' 's' 's']
 ['s' 's' 's' 's']
 ['s' 's' 's' 's']]


##### NOTE: Try empty_like, ones_like_, zeros_like, full_like

## B. Creation with Numerical Ranges

### 1. Evenly spaced values within a given interval

In [13]:
print(np.arange(10))                   # Creates array elements in range of 0 to 10     

print(np.arange(11, 30))               # Creates array elements in range of 11 to 30   

print(np.arange(11, 30, 3))            # Creates array elements in range of 11 to 30 with interval of 3   

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[11 14 17 20 23 26 29]


### 2. Array with evenly spaced numbers over a specified interval

In [19]:
print(np.linspace(0, 1, 5))                  # Elements between 0 and 1 divided into 5 intervals(step)

print(np.linspace(2, 3, 5, retstep=True))    # Will also print the step value

[0.   0.25 0.5  0.75 1.  ]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


### 3. Array with numbers spaced evenly on a log scale

In [17]:
print(np.logspace(0, 1, 5))                  # Elements between 0 and 1 divided into 5 log intervals

print(np.logspace(2, 3, 5, base=2))          # With specific base value

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]
[4.         4.75682846 5.65685425 6.72717132 8.        ]


### 4. Array with numbers spaced evenly on a log scale ( A Geometric Progression)

In [21]:
print(np.geomspace(1, 1000, 4))                  # Elements between 0 and 1000 divided into 5 step

print(np.geomspace(1, 256, 9))                   

[   1.   10.  100. 1000.]
[  1.   2.   4.   8.  16.  32.  64. 128. 256.]


### 5. Meshgrid

In [20]:
x = np.array([0, 1, 2, 3, 4])        # Creates two arrays such that pairing of corresponding element-
y = np.array([0, 1, 2, 3, 4])        # -in each metrix gives the x and y coordinate of a point in the grid.

xx, yy = np.meshgrid(x, y)
print(xx)
print(yy)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


### 6. Create multi dimensional grid

In [22]:
print(np.mgrid[0:5,0:5])

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
