# Numpy_Random Sampling

### 1. Uniformly distributed Random Values in a given shape

In [2]:
import numpy as np

print(np.random.rand(3, 2))                  # uniformly distributed value between 0 and 1

[[0.18216127 0.95997472]
 [0.57754515 0.73768061]
 [0.05498957 0.47598702]]


### 2. Standard Normal distributed Random Values in a given shape

In [5]:
print(np.random.randn(3, 4))                  # Standard Normal distributed

[[-0.85354448  0.55841859 -0.22272018  1.68438542]
 [ 1.02173102  0.05475095 -0.12317566 -0.44707049]
 [ 0.58530055 -1.29977861 -1.55458104 -1.68978761]]


### 3. Random integers arrays

In [18]:
print(np.random.randint(10))                 # Random no till 10

print(np.random.randint(20, size=(2,4)))     

print(np.random.randint(5,20, (2,4))) 

3
[[10 16 18 15]
 [ 6  9 17 17]]
[[11 19 18 19]
 [11 11  6 12]]


### 4.Create an array uniformly distributed in the given range 0 and 1 

In [20]:
print(np.random.random((2,4))) 

[[0.04372214 0.62388414 0.65112975 0.98546373]
 [0.19006687 0.51078895 0.51436971 0.21255614]]
