# Numpy_Math_Statstics Functions

## 1. Order Statistics

### A. Minimum of an array or minimum along an axis

In [2]:
import numpy as np
grid = np.array ([[11, 8, 2, 14],
                  [15, 7, 5, 1],
                  [3, 6, 5, 7 ],
                  [18, 4, 2, 6]])

print(np.amin(grid))               # Minimum of the flattened array
print(np.amin(grid, axis = 0))     # Minimum of the axis = 0 
print(np.amin(grid, axis = 1))     # Minimum of the axis = 1 

1
[3 4 2 1]
[2 1 3 2]


### B. Maximum of an array or minimum along an axis

In [6]:
print(np.amax(grid))               # Minimum of the flattened array
print(np.amax(grid, axis = 0))     # Minimum of the axis = 0 
print(np.amax(grid, axis = 1))     # Minimum of the axis = 1 

18
[18  8  5 14]
[14 15  7 18]


### C. Minimum of an array or minimum along an axis, ignoring any NaNs

In [8]:
mat = np.array ([[11, 8, 2, 14],
                 [15, 7, np.nan, 1 ],
                 [3, 6, 5, 7 ],
                 [18, 4, 2, 6]])

print(np.nanmin(grid))               # Minimum of the flattened array
print(np.nanmin(grid, axis = 0))     # Minimum of the axis = 0 
print(np.nanmin(grid, axis = 1))     # Minimum of the axis = 1 

2.0
[3. 4. 2. 6.]
[2. 5. 3. 2.]


### D. Maximum of an array or minimum along an axis, ignoring any NaNs

In [10]:
print(np.nanmax(grid))               # Minimum of the flattened array
print(np.nanmax(grid, axis = 0))     # Minimum of the axis = 0 
print(np.nanmax(grid, axis = 1))     # Minimum of the axis = 1 

18
[18  8  5 14]
[14 15  7 18]


### E. Percentile (Equivalent to Median)

In [19]:
P = np.array([[10, 7, 4], [3, 2, 1]])
print(P)

print(np.percentile(P, 50))                 # Percentile for flattened Array
print(np.percentile(P, 50, axis=0))         # Percentile for axis = 0
print(np.percentile(P, 50, axis=1))         # Percentile for axis = 1

[[10  7  4]
 [ 3  2  1]]
3.5
[6.5 4.5 2.5]
[7. 2.]


### F. Percentile ignoring NaN Values (Equivalent to Median)

In [18]:
P n= np.array([[np.nan, 7, 4], [3, np.nan, 1]])
print(P)

print(np.nanpercentile(Pn, 50))                 # Percentile for flattened Array
print(np.nanpercentile(Pn, 50, axis=0))         # Percentile for axis = 0
print(np.nanpercentile(Pn, 50, axis=1))         # Percentile for axis = 1

[[nan  7.  4.]
 [ 3. nan  1.]]
3.5
[3.  7.  2.5]
[5.5 2. ]


### G. Quantile

In [21]:
Q = np.array([[10, 7, 4], [3, 2, 1]])
print(Q)

print(np.quantile(Q, 0.5))                 # Percentile for flattened Array
print(np.quantile(Q, 0.5, axis=0))         # Percentile for axis = 0
print(np.quantile(Q, 0.5, axis=1))         # Percentile for axis = 1

[[10  7  4]
 [ 3  2  1]]
3.5
[6.5 4.5 2.5]
[7. 2.]


### G. Quantile ignoring NaN

In [23]:
Qn = np.array([[np.nan, 7, 4], [3, np.nan, 1]])
print(Qn)

print(np.nanquantile(Qn, 0.5))                 # Percentile for flattened Array
print(np.nanquantile(Qn, 0.5, axis=0))         # Percentile for axis = 0
print(np.nanquantile(Qn, 0.5, axis=1))         # Percentile for axis = 1

[[nan  7.  4.]
 [ 3. nan  1.]]
3.5
[3.  7.  2.5]
[5.5 2. ]


NOTE : 1. Percentile is equivalent to median with q in the range[0, 50].
       2. Quantile is equivalent to median with q in the range[0, 0.5].
       3. Percentile is quivalent to Quantile with q in the range[0, 100].

## 2. Averages and Variances

In [31]:
test =  np.array ([[11, 8, 2, 14],
                  [15, 7, 5, 1],
                  [3, 6, 5, 7 ],
                  [18, 4, 2, 6]])

### A. Median

In [34]:
print(np.median(test))                # Median of the Flattened Array
print(np.median(test, axis = 0))      # Median along axis 0
print(np.median(test, axis = 1))      # Median along axis 1

# Try nanmedian

6.0
[13.   6.5  3.5  6.5]
[9.5 6.  5.5 5. ]


### B. Average

In [35]:
print(np.average(test))                # Average of the Flattened Array
print(np.average(test, axis = 0))      # Average along axis 0
print(np.average(test, axis = 1))      # Average along axis 1

7.125
[11.75  6.25  3.5   7.  ]
[8.75 7.   5.25 7.5 ]


In [39]:
test2 = np.array([[0, 1],
                  [2, 3],
                  [4, 5]])

print(np.average(test2, axis=1, weights=[1./4, 3./4]))    # With weight along axis

[0.75 2.75 4.75]


### B. Mean

In [42]:
test3 = np.array([[1, 2], [3, 4]])

print(test3)

print(np.mean(test3))                  # Mean of the Flattened Array
print(np.mean(test3, axis=0))          # Mean along axis 0
print(np.mean(test3, axis=1))          # Mean along axis 1

# Try nanmean

[[1 2]
 [3 4]]
2.5
[2. 3.]
[1.5 3.5]


### C. Standard Deviation

In [45]:
test3 =  np.array ([[11, 8, 2, 14],
                    [15, 7, 5, 1],
                    [3, 6, 5, 7 ],
                    [18, 4, 2, 6]])

print(np.std(test3))                   # Standard deviation of flattned Array
print(np.std(test3, axis=0))           # Standard deviation along axis 0
print(np.std(test3, axis=1))           # Standard deviation along axis 1

# Try nanstd

4.8202048711647105
[5.62916512 1.47901995 1.5        4.63680925]
[4.43705984 5.09901951 1.47901995 6.2249498 ]


### D. Variance 

In [4]:
test4 = np.array([[1, 2], [3, 4]])

print(np.var(test4))                   # Variance of flattned Array
print(np.var(test4, axis=0))           # Variance along axis 0
print(np.var(test4, axis=1))           # Varience along axis 1

# Try nanvar

1.25
[1. 1.]
[0.25 0.25]
