# Numpy : uFunc : Math : Linear Algebra

## A. Matrix and Vector Products

### 1. Dot Product

1. If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
2. If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.
3. If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.
4. If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
5. If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last    axis of b.

In [4]:
import numpy as np
from numpy import linalg as LA
from numpy import linalg as LAb

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[1, 2],
              [2, 1],
              [1, 2]])

# Dot Produt of two Arrays

Dprod = np.dot(X, Y)
print(Dprod)

[[ 8 10]
 [20 25]
 [32 40]]


In [10]:
# Scalar Dot product
R = np.random.randint(5, size =(1, 10))
print(R)

R_dot = np.dot(R, 2)
print(R_dot)

[[0 1 0 0 3 4 1 4 2 0]]
[[0 2 0 0 6 8 2 8 4 0]]


### 2. Inner Product

In [46]:
a1 = np.array([1, 2, 3])

b1 = np.array([1, 2, 1])

# Inner product of two 1-D array 
print(np.inner(a1, b1))

8


In [16]:
a2 = np.array([1, 2, 3])

b2 = np.array([[1, 1, 1],
               [1, 2, 2]])

# Inner product of two 1-D array and 2-D array 
print(np.inner(a2, b2))

[ 6 11]


In [20]:
a3 = np.array([[1, 2, 3],
               [1, 2, 2]])

b3 = np.array([[1, 1, 1],
               [1, 2, 2]])

# Inner product of two 2-D array and 2-D array 
print(np.inner(a3, b3))

[[ 6 11]
 [ 5  9]]


In [27]:
a4 = np.array([[3, 6, 9],
               [2, 4, 8],
               [1, 3, 5]])

# Inner product of Array and scalar 
print(np.inner(a4, 3))

[[ 9 18 27]
 [ 6 12 24]
 [ 3  9 15]]


### 3. Outer Product

In [28]:
a1 = np.array([1, 2, 3])

b1 = np.array([1, 1, 1])

# Outer product of two 1-D array 
print(np.outer(a1, b1))

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [29]:
a2 = np.array([1, 2, 3])

b2 = np.array([[1, 1, 1],
               [1, 2, 2]])

# Outer product of two 1-D array and 2-D array 
print(np.outer(a2, b2))

[[1 1 1 1 2 2]
 [2 2 2 2 4 4]
 [3 3 3 3 6 6]]


In [31]:
a3 = np.array([[1, 2, 3],
               [1, 2, 2]])

b3 = np.array([[1, 1, 1],
               [1, 2, 2]])

# Inner product of two 2-D array and 2-D array 
print(np.outer(a3, b3))

[[1 1 1 1 2 2]
 [2 2 2 2 4 4]
 [3 3 3 3 6 6]
 [1 1 1 1 2 2]
 [2 2 2 2 4 4]
 [2 2 2 2 4 4]]


In [34]:
a4 = np.array([[3, 6, 9],
               [2, 4, 8],
               [1, 3, 5]])

# Inner product of Array and scalar 
print(np.outer(3, a4))
print(np.outer(a4, 3))

[[ 9 18 27  6 12 24  3  9 15]]
[[ 9]
 [18]
 [27]
 [ 6]
 [12]
 [24]
 [ 3]
 [ 9]
 [15]]


### 3. Vector Dot Product

In [42]:
v1 = np.array([1, 2, 3])               
w1 = np.array([2, 3, 3])               
              

# Vector dot product 1-D Arrays
print(np.vdot(v1, w1))

17


In [45]:
v2 = np.array([[1, 2],
               [2, 2]])               
w2 = np.array([[2, 3],
               [1, 1]]) 

# Vector product 2-D Arrays 
print(np.vdot(v2, w2))

12


### 4. Matrix Multiplication

In [58]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[1, 2],
              [2, 1],
              [1, 2]])

# Matrix Multiplication of 2D Arrays

print(np.matmul(X, Y))

[[ 8 10]
 [20 25]
 [32 40]]


## B. Matrix Eigen values and vectors

In [71]:
mat = np.diag([1, 2, 3])
print(mat)

e, f = LA.eig(mat)

print("Eigen Values: ", e)                      # Eigen Values

print("Eigen Vector:\n ", f)                    # Eigen Vectors

print("Eigen Values: ", LA.eigvals(mat))        # Eigen value

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen Values:  [1. 2. 3.]
Eigen Vector:
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eigen Values:  [1. 2. 3.]


## C. Solving Matrices

### 1. Solve simple linear equation

In [22]:
# To solve the system of equations 3*x1 + x2 = 9 and x1 + 2*x2 =8

matA = np.array([[3, 1],
                [1, 2]])
matB = np.array([9, 8])

sol = np.linalg.solve(matA, matB)               # solve for x1 and x2
print(sol)            

print(np.allclose(np.dot(matA, sol), matB))     # Check solution is Correct

[2. 3.]
True


### 2. Compute (Multiplicative) inverse of matrix

In [79]:
print(np.linalg.inv(matA))                      # Inverse of the matrix

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [82]:
#Inverse of several matrices at once

grid = np.array([[[1, 2], [3, 4]], [[1, 3], [3, 5]]])

print(np.linalg.inv(grid))

[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]
