# Numpy_Math_Set Operations

## 1. Unique elements of the array

In [1]:
import numpy as np

A = np.array([1, 1, 2, 3, 3, 5, 5, 5])

print(np.unique(A))                        # Print unique elements of the 1D array 

[1 2 3 5]


In [3]:
B = np.array([[1, 1, 1],                   
              [2, 3, 4],
              [2, 3, 3]])
              
print(np.unique(B))                        # Print unique elements of the 2D array

[1 2 3 4]


In [7]:
C = np.array([[1, 1, 1],
              [2, 4, 6],
              [1, 1, 1]])
              
print(np.unique(C, axis = 0))                # Finding Unique Row i.e axis=0

[[1 1 1]
 [2 4 6]]


In [6]:
D = np.array([[1, 1, 1],
              [2, 4, 2],
              [1, 1, 1]])

print(np.unique(D, axis=1))                # Finding Unique Column i.e axis=1

[[1 1]
 [2 4]
 [1 1]]


In [11]:
# Return the indices of the unique elements 

E = np.array(['t', 'r', 'e', 'e', 's'])

u, indices = np.unique(E, return_index=True)

print(u)
print(indices)

['e' 'r' 's' 't']
[2 1 4 0]
[2 1 4 0]


## 2. Set Boolean Operation

### A. Test for presence of each element of 1-D array in a second array

In [14]:
set1 = np.array([0, 1, 2, 5, 0])
set2 = np.array([0, 5])

test1 = np.in1d(set1, set2)                 # Common elements

print(test1)
print(set1[test1])                          # Print common elements

test2 = np.in1d(set1, set2, invert=True)    # Uncommon elements

print(test2)
print(set1[test2])                          # Print Uncommon elements


[ True False False  True  True]
[0 5 0]
[False  True  True False False]
[1 2]


### B. Intersection of two arrays 1-D

In [16]:
X = np.intersect1d(['a', 'k', 'a', 's', 'h'], ['s', 'h', 'r', 'e', 'y', 'a'])

print(X)

['a' 'h' 's']


### C. Union of two arrays 1-D

In [20]:
Y = np.union1d(['a', 'k', 'a', 's', 'h'], ['s', 'h', 'r', 'e', 'y', 'a'])

print(Y)

['a' 'e' 'h' 'k' 'r' 's' 'y']


### D. Set difference of two arrays 1-D

In [23]:
U1 = np.setdiff1d([1, 2, 3, 4, 5, 6, 7], [1, 3, 5, 7])
print(U1)                                                 

[2 4 6]


### E. Set exculsive or of two arrays 1-D

In [30]:
U2 = np.setxor1d([1, 3, 5, 3, 8, 1], [1, 2, 3, 5, 2, 6, 7])

print(U2)                                                   # Sorted Unique values present in only one (not both) arrays

[2 6 7 8]


### F. Calculate element in test_elements, broadcasting over element only

In [37]:
element = 2*np.arange(4).reshape((2,2))

print(element)

test_elements = [1, 2 , 4, 8]

result = np.isin(element, test_elements)

print(result)

print(element[result])


[[0 2]
 [4 6]]
[[False  True]
 [ True False]]
[2 4]
