# Working with different data file formats (I/O)

### 1. Save and Load a binary files (NPY, NPZ)

In [26]:
import numpy as np

np.save('D:/ABC/file', np.array([[1, 2, 3], [4, 5, 6]]))

X = np.load('D:/ABC/file.npy')

print(X)

[[1 2 3]
 [4 5 6]]


### 2. Save and Load a Text file (TXT)

In [37]:
np.savetxt('D:/ABC/textfile.txt', np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))       # Save a txt File

Y = np.loadtxt('D:/ABC/textfile.txt')                                                # Load a txt File

print(Y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 3. Creating array from text data in a string

In [45]:
Z = np.fromstring('1, 2', sep=',')
print(Z)

Z = np.fromstring('1 2', sep=' ')
print(Z)

[1. 2.]
[1. 2.]
