# Numpy : Fancy and Combined Indexing

### 1. Fancy Indexing

In [22]:
import numpy as np

In [23]:
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [24]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [25]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [26]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

### 2. Combined Indexing

In [27]:
X = np.arange(12).reshape((3, 4))
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# Fancy and simple indices
X[2, [2, 0, 1]]

array([10,  8,  9])

In [29]:
# Combine fancy indexing with slicing
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

### 3. Modifying Values with Fancy Indexing

In [30]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [31]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


### 4. Array Selection using index

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
bool_arr = arr > 4

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])